package com.backend.entity;

public enum ExperienceReportReason {
    INAPPROPRIATE_CONTENT,
    MISLEADING_DESCRIPTION,
    SAFETY_CONCERNS,
    SPAM,
    FRAUDULENT,
    HARASSMENT_OR_ABUSE,
    INAPPROPRIATE_IMAGES,
    FALSE_INFORMATION,
    PRICING_ISSUES,
    CANCELLATION_POLICY_ISSUES,
    POOR_SERVICE,
    UNSAFE_CONDITIONS,
    OTHER
}

