package com.backend.entity;

public enum NotificationType {
    BOOKING_CONFIRMATION,
    REMINDER,
    DISCOUNT,
    MESSAGE,
    REVIEW_REQUEST,
    PASSWORD_RESET,
    UPDATE_INFO,
    EMAIL_UPDATE,
    KYC_STATUS,
    BOOKING_CANCELLED,
    EXPERIENCE_UPDATE,
    EXPERIENCE_SUSPENDED,
    EXPERIENCE_STATUS_CHANGE
}
